version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ytaskAdmin
      POSTGRES_PASSWORD: ytask1337
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: mvt

  ytask-api:
    build:
      context: ./
    # image: ytaskwns/ytask-api:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CLIENT_WHITELIST: ${CLIENT_WHITELIST}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SUPER_ADMIN_NAME: ${SUPER_ADMIN_NAME}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    ports:
      - '4000:4000'
    volumes:
      - ./src/:/app/src/
    command: npm run deploy

  nginx:
    image: nginx:1.21.3
    depends_on:
      - ytask-api
    restart: always
    ports:
      - ${GATEWAY_PORT:-4000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

volumes:
  postgres:
