version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ytaskAdmin
      POSTGRES_PASSWORD: ytask1337
    volumes:
      - postgres:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: mvt

  # ytask:
  #   build:
  #     context: ./
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./src/:/app/src/
  #   command: npm run dev

  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #   ports:
  #     - '80:80'

volumes:
  postgres:
